# Generated by Django 6.1 on 2026-08-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='Запрос пользователя')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('platform', models.CharField(choices=[('tg', 'Telegram'), ('vc', 'VC.ru'), ('tw', 'Twitter/X')], default='tg', max_length=2, verbose_name='Платформа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сгенерированный пост',
                'verbose_name_plural': 'Сгенерированные посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
