# Generated by Django 6.1 on 2026-08-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код тарифа (slug)')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('price', models.IntegerField(verbose_name='Цена (руб)')),
                ('period', models.CharField(max_length=20, verbose_name="Период (например, '/ месяц')")),
                ('generations_limit', models.IntegerField(verbose_name='Лимит генераций в сутки')),
                ('features', models.JSONField(verbose_name='Список возможностей (массив строк)')),
                ('is_popular', models.BooleanField(default=False, verbose_name="Метка 'Популярно'")),
                ('weight', models.IntegerField(default=0, verbose_name='Вес (для апгрейдов/даунгрейдов)')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='Запрос пользователя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('platform', models.CharField(choices=[('tg', 'Telegram'), ('vc', 'VC.ru'), ('tw', 'Twitter/X')], default='tg', max_length=2, verbose_name='Платформа')),
                ('status', models.CharField(choices=[('processing', 'Генерируется ИИ'), ('completed', 'Готово'), ('failed', 'Ошибка генерации')], default='processing', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сгенерированный пост',
                'verbose_name_plural': 'Сгенерированные посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generations_left', models.IntegerField(default=3, verbose_name='Осталось генераций')),
                ('last_reset', models.DateField(auto_now_add=True, verbose_name='Дата сброса лимитов')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='posts.pricingplan', verbose_name='Тариф')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
