# Generated by Django 6.1 on 2026-08-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='status',
            field=models.CharField(choices=[('processing', 'Генерируется ИИ'), ('completed', 'Готово'), ('failed', 'Ошибка генерации')], default='processing', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
    ]
