# Generated by Django 6.1 on 2026-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_generatedpost_status_alter_generatedpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('standard', 'Стандарт'), ('pro', 'Бизнес'), ('max', 'Максимум')], default='free', max_length=10, verbose_name='Тариф'),
        ),
    ]
