# Generated by Django 6.1 on 2026-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код платформы (slug, например, tg)')),
                ('name', models.CharField(max_length=50, verbose_name='Название (для фронтенда)')),
                ('system_instruction', models.TextField(verbose_name='Системная инструкция для OpenAI')),
            ],
            options={
                'verbose_name': 'ИИ-Платформа',
                'verbose_name_plural': 'ИИ-Платформы',
            },
        ),
        migrations.CreateModel(
            name='AITone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код тональности (slug, например, business)')),
                ('name', models.CharField(max_length=50, verbose_name='Название (для фронтенда)')),
                ('instruction_text', models.TextField(verbose_name='Текст инструкции (добавляется к промпту)')),
            ],
            options={
                'verbose_name': 'Тональность текста',
                'verbose_name_plural': 'Тональности текста',
            },
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='platform',
            field=models.CharField(max_length=10, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='status',
            field=models.CharField(default='processing', max_length=15, verbose_name='Статус'),
        ),
    ]
