version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ai_helper_db
    restart: always
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_DB: ai_content_db
    ports:
      - "5432:5432" # Вынесли стандартный порт наружу для удобства локальной отладки
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_content_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ai_helper_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: ./ai_content_helper_back
    # Команда сначала ждет БД, делает миграции, а затем запускает сервер
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py init &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./ai_content_helper_back:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build: ./ai_content_helper_back
    command: celery -A core worker --loglevel=info
    volumes:
      - ./ai_content_helper_back:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # frontend:
  #   # Переключаем Docker на production сборку
  #   build:
  #     context: ./ai_content_helper_front
  #     dockerfile: Dockerfile.prod
  #     args:
  #       - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
  #       - VITE_API_URL=${VITE_API_URL}
  #   container_name: ai_helper_front
  #   # В prod-режиме volumes больше не нужны, код «запекается» внутри образа
  #   env_file:
  #     - .env
  #   depends_on:
  #     - web

  frontend:
    build:
      context: ./ai_content_helper_front
      dockerfile: Dockerfile  
    container_name: ai_helper_front
    ports:
      - "5173:5173"
    volumes:
      - ./ai_content_helper_front:/app  
      - /app/node_modules            
    env_file:
      - .env
    depends_on:
      - web


  gateway:
    image: caddy:2-alpine
    container_name: ai_gateway
    restart: always
    ports:
      - "80:80"   # Для проверки домена
      - "443:443" # Для безопасного HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
