# Шаг 1: Сборка статики
FROM node:20-alpine AS build
WORKDIR /app

# --- ДОБАВЛЯЕМ ЭТИ СТРОКИ: Объявляем переменные для сборщика ---
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_API_URL
# Делаем их доступными для NodeJS/Vite во время npm run build
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_API_URL=$VITE_API_URL
# -------------------------------------------------------------

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Шаг 2: Раздача через Nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
